config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :show, :new, :create] do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  #validates :name, presence: true
  #validates :address, presence: true
  #validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
     @restaurant = Restaurant.new(params_restaurant)
     if @restaurant.save
      redirect_to :restaurants
     else
      render :create
     end
  end

  private

  def params_restaurant
    params.require(:restaurant).permit(:name, :address, :category, :phone)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to :restaurants
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container" style="padding-top:2em;">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
    <div class="col-sm-4">
       <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/500/400/?random');">
        <div class="card-description">
          <h2><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h2>
          <p><%= restaurant.address %></p>
        </div>
      </div>
    </div>
   <% end %>
 </div>
</div>

app/views/restaurants/new.html.erb
<h3>Ajouter une restaurant</h3>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: 'Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :address, label: 'Address', error: 'Username is mandatory, please specify one' %>
  <%= f.input :phone, label: 'Phone', error: 'Username is mandatory, please specify one' %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
      <h2><%= @restaurant.name %></h2>
      <h3><%= @restaurant.phone %></h3>
      <h4><%= @restaurant.address %></h4>
      <%= link_to "ajouter review", new_restaurant_review_path(@restaurant)  %>
      <% @reviews.each do |review| %>
      <%= review.content %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Ajouter un restaurant", new_restaurant_path, class: 'navbar-wagon-item navbar-wagon-link' %>


  </div>
</div>